FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ChatSentimentAPI.csproj", "./"]
RUN dotnet restore "ChatSentimentAPI.csproj"
COPY . .
RUN dotnet build "ChatSentimentAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ChatSentimentAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ChatSentimentAPI.dll"]